services:
  api:
    volumes:
      - ./geoshop-back:/app/geoshop_back:rw
    command: 
      - bash
      - -c
      - "python3 manage.py runserver 0.0.0.0:8000"

  proxy:
    image: nginxinc/nginx-unprivileged:stable
    depends_on:
      - api
      - front
    ports:
      - "443:443"
    networks:
      - geoshop
    volumes:
      - ./local-dev/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./local-dev/certs:/etc/nginx/certs:ro

  front-dev:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    networks:
      - geoshop
    volumes:
      - ./front:/usr/app:rw
