services:
  proxy:
    image: nginxinc/nginx-unprivileged:stable
    depends_on:
      - api
      - front
    ports:
      - "443:443"
    networks:
      - geoshop
    volumes:
      - ./nginx-local-dev/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx-local-dev/certs:/etc/nginx/certs:ro